#生產環境
server:
  port: 8080
spring:
  config:
    import: "file:./dataSource.properties"
  datasource:
#    url: jdbc:mysql://webserverdb-1.cdiqm6eo6153.ap-northeast-3.rds.amazonaws.com:3306/1rm_demo
#    username: admin
#    password: SeanIsCoding#^(
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: ${db.driver-class-name}
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  data:
    redis:
      host: localhost
      port: 6379
logging:
  config: classpath:logback-dev.xml
mybatis:
  configuration:
    #MySQl中已下滑線命名的字段可以和實體類中的駝峰命名屬性自動轉換
    map-underscore-to-camel-case: true